# Generated by Django 4.2.7 on 2023-12-13 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(blank=True, max_length=2000, null=True)),
                ('recordid', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(max_length=25)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.fieldgroup')),
            ],
        ),
        migrations.AddField(
            model_name='websiteaccount',
            name='field_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Account.fieldgroup'),
        ),
    ]
