# Generated by Django 4.2.7 on 2023-12-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_remove_website_name_alter_field_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='callback_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
