# Generated by Django 4.2.7 on 2023-12-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_alter_websiteaccount_user_id_on_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='callback_url',
            field=models.URLField(default='/callback'),
            preserve_default=False,
        ),
    ]
