# Generated by Django 4.2.7 on 2023-12-17 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_alter_website_callback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='birth_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='first_name',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='last_name',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
