# Generated by Django 4.2.7 on 2024-01-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_website_birth_date_website_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='website',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='website',
            name='last_name',
        ),
        migrations.AddField(
            model_name='website',
            name='logo',
            field=models.ImageField(blank=True, default='images/logos/default.png', null=True, upload_to='images/logos'),
        ),
    ]
